### ISSUE TITLE
No such container error

### ISSUE THREAD

**Issue by rocketraman** [sematext/sematext-agent-docker#14]
SDA container exits with:

```
2016-08-05T02:19:08.445432842Z 2016-08-05T02:19:08.339Z - ERROR - Please contact support@sematext.com to report the error:
2016-08-05T02:19:08.446000871Z 2016-08-05T02:19:08.393Z - ERROR - UncaughtException:Error: (HTTP code 404) no such container - No such container: 3edaeb2c7a3c2354eb85ec675c65b45c053d61b21435ea066f49f8d9c82dd148
2016-08-05T02:19:08.446010838Z  
2016-08-05T02:19:08.446014472Z   Error: (HTTP code 404) no such container - No such container: 3edaeb2c7a3c2354eb85ec675c65b45c053d61b21435ea066f49f8d9c82dd148
2016-08-05T02:19:08.446017831Z  
2016-08-05T02:19:08.446020873Z     at /usr/lib/node_modules/sematext-agent-docker/node_modules/docker-modem/lib/modem.js:229:17
2016-08-05T02:19:08.446024036Z     at getCause (/usr/lib/node_modules/sematext-agent-docker/node_modules/docker-modem/lib/modem.js:259:7)
2016-08-05T02:19:08.446027352Z     at Modem.buildPayload (/usr/lib/node_modules/sematext-agent-docker/node_modules/docker-modem/lib/modem.js:228:5)
2016-08-05T02:19:08.446030815Z     at IncomingMessage.<anonymous> (/usr/lib/node_modules/sematext-agent-docker/node_modules/docker-modem/lib/modem.js:204:14)
2016-08-05T02:19:08.446045087Z     at emitNone (events.js:91:20)
2016-08-05T02:19:08.446048170Z     at IncomingMessage.emit (events.js:185:7)
2016-08-05T02:19:08.446051030Z     at endReadableNT (_stream_readable.js:926:12)
2016-08-05T02:19:08.446053815Z     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-08-05T02:19:08.446056675Z     at process._tickCallback (internal/process/next_tick.js:98:9)
```

This is the `:latest` container.

**Comment by megastef** [comment]
Which version of docker engine?

**Comment by megastef** [comment]
Could you please tell us how to reproduce the it? Do you have a "recording" docker events for container 3edaeb2c7a3c2354eb85ec675c65b45c053d61b21435ea066f49f8d9c82dd148 (e.g. in SPM) at that time? Did this happen once, or frequently?

**Comment by rocketraman** [comment]
> Which version of docker engine?

Docker 1.11.1-cs1

> Could you please tell us how to reproduce the it?

I don't know, I've only seen it twice, both times on our AWS cluster.

> Do you have a "recording" docker events for container 3edaeb2c7a3c2354eb85ec675c65b45c053d61b21435ea066f49f8d9c82dd148 (e.g. in SPM) at that time?

I don't see anything related to this container in SPM, but I'm not sure I'm looking for it properly. I'm not sure how to build an SPM query for container. Searching for `container_id:3edaeb2c7a3c2354eb85ec675c65b45c053d61b21435ea066f49f8d9c82dd148` in logsene shows nothing.

> Did this happen once, or frequently?

Twice only that I've seen so far.

**Comment by megastef** [comment]
@rocketraman Can we close this issue? Pls. check 1.30.20

**Comment by rocketraman** [comment]
@megastef Yes I haven't seen this lately. Thx!
