### ISSUE TITLE
My container is not forwarding logs

### ISSUE THREAD

**Issue by ghost** [sematext/sematext-agent-docker#2]
So this how am running the containter

sematext-agent-docker:
  image: 'sematext/sematext-agent-docker:latest'
  deployment_strategy: every_node
  environment:
    - LOGSENE_TOKEN=XXXXX
    - SPM_TOKEN=xxxxxx
  privileged: true
  restart: always
  tags:
    - production
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'

So if I check at the logs am getting this:

Tutum Node Hostname: ccf49792-tumacredo
2015-12-17T08:35:24.820472622Z No pattern file for log parsing found /etc/logagent/patterns.yml -> using default patterns
2015-12-17T08:35:24.822308761Z Use -v /mypattern/patterns.yml:/etc/logagent/patterns.yml for custom log parser definitions.
2015-12-17T08:35:24.933736811Z Listening for "journalctl -o json | ncat localhost PORT" on exposed port 9000
2015-12-17T08:35:24.955305427Z Thu, 17 Dec 2015 08:35:24 GMT uncaughtException: connect ENOENT /var/run/docker.sock
2015-12-17T08:35:24.955449467Z Error: connect ENOENT /var/run/docker.sock
2015-12-17T08:35:24.955462697Z     at Object.exports._errnoException (util.js:874:11)
2015-12-17T08:35:24.955467953Z     at exports._exceptionWithHostPort (util.js:897:20)
2015-12-17T08:35:24.955472717Z     at PipeConnectWrap.afterConnect [as oncomplete](net.js:1063:14)
2015-12-17T08:35:24.955857719Z Thu, 17 Dec 2015 08:35:24 GMT uncaughtException: connect ENOENT /var/run/docker.sock
2015-12-17T08:35:24.955988595Z Error: connect ENOENT /var/run/docker.sock
2015-12-17T08:35:24.955999644Z     at Object.exports._errnoException (util.js:874:11)
2015-12-17T08:35:24.956004458Z     at exports._exceptionWithHostPort (util.js:897:20)
2015-12-17T08:35:24.956008948Z     at PipeConnectWrap.afterConnect [as oncomplete](net.js:1063:14)

**Comment by megastef** [comment]
Hi,

the Agent has no access to the docker unix socket 

```
volumes: '/var/run/docker.sock:/var/run/docker.sock'
```

Potential reasons: 
- different location of the Docker Unix Socket? SSH to the node and check with 'ls -la /var/run/docker.sock'
- Configured TLS socket instead? -> the we have to configure TLS access  

Please let me know:
- Using Tutum Cloud?
- Provider, which runs your node (DigitalOcean, Amazon AWS, ...) 
- Operating system of the Docker Host 
- Configuration of the docker daemon

**Comment by ghost** [comment]
Am using tutum cloud.
Provider: CenturyLink
Operating system: Ubuntu 14

I have checked permessions and am getting this:

~# ls -la /var/run/docker.sock
srw-rw---- 1 root docker 0 Dec 16 10:26 /var/run/docker.sock

**Comment by ghost** [comment]
With help from @megastef  I have  figured out the issue is on tutum side, they don't specify the volume of  the container thats why the container was failing. I have reported the issue to tutum but for now you can work around that by removing the tags and it will work

**Comment by megastef** [comment]
Thanks - going to close the issue.
I hope Tutum gets the issue solved - maybe it helps to put the "tags" parameter bind the "volumes" parameter in the Stackfile? Pls. let us know the result from Tutum Support.

**Comment by ghost** [comment]
will let you know
