### ISSUE TITLE
TypeError: Cannot read property 'REMOVE_FIELDS' of undefined

### ISSUE THREAD

**Issue by Uter1007** [sematext/sematext-agent-docker#49]
With the installation of the newest helm chart, I will receive the following error. 

setting LOGSENE_ENABLED=true
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'REMOVE_FIELDS' of undefined
      at removeFields (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:58:33)
      at processAnnotations (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:129:5)
      at /usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:189:9
      at getPodSpec (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:47:5)
      at process._tickCallback (internal/process/next_tick.js:68:7) } reason:  TypeError: Cannot read property 'REMOVE_FIELDS' of undefined
    at removeFields (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:58:33)
    at processAnnotations (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:129:5)
    at /usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:189:9
    at getPodSpec (/usr/local/lib/node_modules/@sematext/logagent/lib/plugins/output-filter/kubernetes-enrichment.js:47:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Uter1007** [comment]
Ok just saw this: https://github.com/sematext/logagent-js/releases/tag/3.0.2

**Comment by otisg** [comment]
@Uter1007 so problem solved?
Also, please note this repo has been deprecated.  Logagent repo is the one where you found the release notes: https://github.com/sematext/logagent-js

**Comment by Uter1007** [comment]
Just trying this out: https://sematext.com/docs/logagent/output-filter-kubernetes/

**Comment by Uter1007** [comment]
hmm still fighting with the new annotations

**Comment by Uter1007** [comment]
I switched back to the old 2 Version cuz I am not able to fix it on my side...

**Comment by megastef** [comment]
I think we fixed the helm chart - make sure you use sematext/logagent:3.0.2

**Comment by megastef** [comment]
Closing, in favor of new issue in Logagent repository: https://github.com/sematext/logagent-js/issues/174 

Please open in Logagent a new issue explaining your issues with annotations. 

You can tag you application container with a logs token, or other interpreted annotations. 
Evaluates pod annotations for Sematext Cloud:
- `sematext/logs-token=YOUR_LOGS_TOKEN` to set the log index
- `sematext/logs-enabled=<true|false>` to switch logging per pod on or off
- `sematext/logs-remove-fields=<field list>` to remove specific log fields from pod logs

E.g. 

``` 
apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    sematext/logs-token=YOUR_LOGS_TOKEN
    # sematext/logs-remove-fields=logSource,labels 
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```
